### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by jeanphilippegg**
Small cleanups. Check the individual commits.

### CODE REVIEW

**Comment by jeanphilippegg** [comment]
Wait a few minutes before merging. There is a small issue.

**Comment by protesilaos** [comment]
Thank you!

I have not tested this: could `denote--format-front-matter-keywords` and `denote--format-front-matter` still need the fallback conditions?

For the new `denote-link-button-action`, we need to make the old an obsolete alias.  Someone may be using it, so better warn them about the change.

**Comment by jeanphilippegg** [comment]
> I have not tested this: could `denote--format-front-matter-keywords` and `denote--format-front-matter` still need the fallback conditions?

I checked. In the one place we do not set it, we let-bind `denote-file-type` to set it indirectly. It is better to set it directly.

> For the new `denote-link-button-action`, we need to make the old an obsolete alias. Someone may be using it, so better warn them about the change.

Yes. I already did this!

I am still working on one more cleanup, if you want to wait a few minutes.

**Comment by protesilaos** [comment]
> I checked. In the one place we do not set it, we let-bind `denote-file-type` to set it indirectly. It is better to set it directly.

Very well!

> Yes. I already did this!

Oh, sorry!  I missed it.

> I am still working on one more cleanup, if you want to wait a few minutes.

Please take as much time as you need.  We are not in a hurry.

**Comment by jeanphilippegg** [comment]
Done!

**Comment by protesilaos** [comment]
Merged.  Thank you!

**Comment by protesilaos** [comment]
Do you think you will make any other changes within the next hours or days?  Just asking because I believe this is the right time to release version `0.5.0`.

The only task that remains is to write a helper command to migrate Denote+Org users who had `#+filetags:  one  two` and need to convert to `#+filetags:  :one:two:`.  This probably needs to stay in the manual, as it is not pertinent to denote.el.

**Comment by jeanphilippegg** [comment]
> Do you think you will make any other changes within the next hours or days? Just asking because I believe this is the right time to release version `0.5.0`.

No, I don't think I have anything else for the short term!

However, I just noticed that `denote--date` uses `denote-file-type`, but I have removed the let-bindings of `denote-file-type`. So I need to fix thix before 0.5.0 is done.

**Comment by jeanphilippegg** [comment]
Done. See pull request #83.

**Pull request merged**
