### PR TITLE
add function denote-org-capture-with-defaults

### PR DESCRIPTION
**Pull request by kimothy**
Hi @protesilaos. First of all. Thanks for the excellent work on the denote package. I use it every day and I really appreciate the work you have put into it.

I would like to propose an additional function to denote.el, named denote-org-capture-with-defaults. It very similar to the denote-org-capture-with-prompts, but instead of constructing a minibuffer prompt for each non-nil argument, it produces one for each nil argument instead. In addition, the arguments that are passed, are used as passed.

This is practical with the org-mode-capture when you want to limit the the user input. For example, if you have org-capture for a journal entry, you might want to default the subdirectory, tags, title and so on, and prompt the user only for what might differ for the template.

A minimal example of use:

```
(setq denote-org-capture-specifiers "%?")

(setq denote-templates
      '((journal . "* Entry\n")))

(with-eval-after-load 'org-capture
  (add-to-list 'org-capture-templates
      '("j" "Journal Entry" plain
        (file denote-last-path)
        (function (lambda () (denote-org-capture-with-defaults "My Journal Entry" '("journal" "entry") "journal-subdir" nil (alist-get 'journal denote-templates))))
        :no-save t
        :immediate-finish nil
        :kill-buffer t
        :jump-to-captured t)))
```

This specific example captures a note with a specific title, a specific set of tags, into a specific subdirectory using todays date, and with a specific template. The user does not need to be prompted in this case, and the capture buffer will open immediately.

An other example of a org-capture template might be:
```
(setq denote-templates
      '((journal . "* TODO \n")))

(with-eval-after-load 'org-capture
  (add-to-list 'org-capture-templates
      '("t" "Todo" plain
        (file denote-last-path)
        (function (lambda () (denote-org-capture-with-defaults nil '("task") "todo-subdir" nil (alist-get 'todo denote-templates))))
        :no-save t
        :immediate-finish nil
        :kill-buffer t
        :jump-to-captured t)))
```
This would prompt the user for a title, but default the tags, subdir, date, template template is defaulted, which makes it very efficient.

Let me know if you have any comments. Thanks a lot.

### CODE REVIEW

**Comment by jeanphilippegg** [comment]
There was a similar case recently (#241) where we wanted interactivity for *some* prompts only. In `denote-org-extras-extract-subtree`, we wanted to have some prompts and set the values of the title and keywords components.

Your use case is valid. I suggest a more general approach to allow this to work with any denote command.

My suggestion is as follow:

Introduce the variables `forced-title`, `forced-keywords`, `forced-file-type`, `forced-subdirectory`, `forced-date`, `forced-signature`. These variables, along with `denote-prompts`, would allow any denote command to be configured to meet one's need in term of interactivity.

Here is how you would configure `denote-org-capture`:

```
(with-eval-after-load 'org-capture
  (add-to-list 'org-capture-templates
      '("t" "Todo" plain
        (file denote-last-path)
        (function (lambda () (let ((denote-prompts '(title))
                                                (forced-keywords '("journal"))
                                                (forced-template 'journal))
                                            (denote-org-capture))))
        :no-save t
        :immediate-finish nil
        :kill-buffer t
        :jump-to-captured t)))
```

I think that reading the above it is obvious what is going to happen.

Maybe this is not necessary for now, but it is worth keeping in minding for when/if someone asks for a `denote-with-defaults` command that prompts for a title, but always set a specific signature.

**Comment by kimothy** [comment]
@jeanphilippegg, thanks for the comment. The function that I wrote is just a slightly modified version of the existing _denote-org-capture-with-defaults_, as such is fits in with the way denote is written today. I do think that your proposal to make it more generic makes sense to.

**Comment by protesilaos** [comment]
Hello @kimothy!

> I do think that your proposal to make it more generic makes sense to.

I also agree with the spirit of @jeanphilippegg point, [as also expressed here](https://github.com/protesilaos/denote/issues/257). As such, I wonder if you want to modify your code to be in line with this approach of generalising how we do things. It will be better for us long-term.

**Comment by jeanphilippegg** [comment]
I have added the `denote-forced-*` variables in my fork of the code, which I will make public this weekend. Pull requests will be made in May.

You may consider closing this pull request, as it will be done (code is ready).

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Mon, 25 Mar 2024 19:07:05 -0700
>
> I have added the `denote-forced-*` variables in my fork of the code,
> which I will make public this weekend. Pull requests will be made in
> May.

Sounds good!

> You may consider closing this pull request, as it will be done (code is ready).

Let's keep this open until then to have a place for discussion. Then we
proceed with the new PR.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
That is right. We should have `denote-use-*` (or with another name) soon.

**Comment by protesilaos** [comment]
Thanks!

**Pull request closed without merging**
