### PR TITLE
Add denote-dired-convert-file-to-denote

### PR DESCRIPTION
**Pull request by jeanphilippegg**
Pull request as discussed in #48.

I added the function in `denote-dired.el`. There is some code duplication between it and `denote-dired-rename-file`.

### CODE REVIEW

**Comment by protesilaos** [comment]
Thank you!

> There is some code duplication

Do you think we should consider this as part of the PR or do it afterwards?  Whatever helps your case.

**Comment by jeanphilippegg** [comment]
> Do you think we should consider this as part of the PR or do it afterwards? Whatever helps your case.

While the code looks similar, it is not exactly the same. I would not know the best way to extract it.

**Comment by protesilaos** [comment]
> I would not know the best way to extract it.

No worries!  I merge this now and we can think about it later.  It is not strictly necessary, anyway.

**Comment by jeanphilippegg** [comment]
> No worries! I merge this now and we can think about it later. It is not strictly necessary, anyway.

Ok, good! Thanks

**Comment by protesilaos** [comment]
I just made some tweaks to the doc string:

```
  "Convert a file to Denote format.

Prompt for a FILE, a TITLE, and KEYWORDS.  The unique identifier
is retrieved from the filename if there is one, else the last
modification time is used to derive one.

In Dired, FILE is the one at point.  It has to be a regular
file (not a directory, a named pipe, etc.).

The default title is retrieved from a line starting with a title
field, depending on the given file type.  Else, the file name is
used.

This command adds a front matter unconditionally at the start of
the file.  It does not check if one is already present.  If a
front matter is already present, you will end up with two.
Consider using `denote-dired-rename-file' in this case.

For per-file-type front matter, refer to the variables:

- `denote-org-front-matter'
- `denote-text-front-matter'
- `denote-toml-front-matter'
- `denote-yaml-front-matter'"
```

Do you think it is okay?

[ I will update the manual later. ]

**Comment by jeanphilippegg** [comment]
Yes. I like it!

**Pull request merged**
