### PR TITLE
Refactor denote--date

### PR DESCRIPTION
**Pull request by jeanphilippegg**
I don't intend to make other changes before 0.5.0.

### CODE REVIEW

**Comment by protesilaos** [comment]
Merged.  Thank you!

Do you have any preference for---or thoughts on---this?  (I believe you are using Org)

> The only task that remains is to write a helper command to migrate Denote+Org users who had `#+filetags:  one  two` and need to convert to `#+filetags:  :one:two:`.  This probably needs to stay in the manual, as it is not pertinent to denote.el.

**Comment by jeanphilippegg** [comment]
> > The only task that remains is to write a helper command to migrate Denote+Org users who had `#+filetags:  one  two` and need to convert to `#+filetags:  :one:two:`.  This probably needs to stay in the manual, as it is not pertinent to denote.el.

If there is nothing broken when manipulating org files, I think we can mention the migration steps in the manual only. Only the functions `denote-rename-file-using-front-matter` and `denote-rename-marked-files-using-front-matter` will not work with old notes.

**Comment by protesilaos** [comment]
> If there is nothing broken when manipulating org files, I think we can mention the migration steps in the manual only. 

Yes, I think the same.

>  Only the functions `denote-rename-file-using-front-matter` and `denote-rename-marked-files-using-front-matter` will not work with old notes.

This, however, suggests we need the command in denote.el so that we "officially" support the migration.  No worries though.  I will work on it today and see what fits better.  Even if it is in denote.el, it will be temporary and shall be deprecated afterwards.

**Comment by jeanphilippegg** [comment]
> This, however, suggests we need the command in denote.el so that we "officially" support the migration. No worries though. I will work on it today and see what fits better. Even if it is in denote.el, it will be temporary and shall be deprecated afterwards.

That's good!

**Pull request merged**
