### PR TITLE
Fix links in non org notes

### PR DESCRIPTION
**Pull request by ggjp**
This fixes links in non org notes.

### CODE REVIEW

**Comment by protesilaos** [comment]
Merged.  Thank you!

**Comment by protesilaos** [comment]
A general comment here.  The creation of `denote--get-note-path-by-id` is a pattern I prefer over `let` binding the function.  I find it easier to work with.

**Comment by ggjp** [comment]
Yes, I wanted to reuse that code elsewhere, so I extracted it in a function. I think it might also be a useful function in the future as well.

Just so I can learn, how did you know that you needed `(eval-when-compile 'cl-lib)`? From where do you get compiler warnings?

**Comment by protesilaos** [comment]
I use `flymake` (built-in) but the `flycheck` package also does the same.

This is my flymake configuration: https://protesilaos.com/emacs/dotemacs#h:b8bfcc05-c0d3-4093-b3fe-f06187d22c6a

And this is the glue code needed for linting Elisp packages: https://protesilaos.com/emacs/dotemacs#h:d03342da-3035-409f-a5e7-5df1e614d507

The `eval-when-compile` part is something I have learnt through experience.  As far as I can tell, it is only needed at compile time because the `;;;###autoload` does not actually load the file at that time.  At runtime, we do not need `(require 'cl-lib)` because the autoloads work.  Maybe I am wrong though, so please double-check.

**Comment by ggjp** [comment]
Ok, thank you! I will check this out!

**Pull request merged**
