### PR TITLE
Added a prompt to denote-rename-file-using-front-matter.

### PR DESCRIPTION
**Pull request by pprevos**
Hi Prot,

I have been using `denote-rename-file-using-front-matter` quite a bite and kept forgetting to save before evoking it so I added a prompt to the function for convenience.

P:)

### CODE REVIEW

**Comment by protesilaos** [comment]
Thank you @pprevos!  This makes sense.  Before I merge it, please tell me what the status is with the copyright assignment to the Free Software Foundation.  Did you do it?

I just ask because you are on the limit of what you can contribute without it and it is better to be on the safe side legally.

**Comment by pprevos** [comment]
Hi Prot,

I have sent the form to FSF a few days ago. No response yet.

**Comment by protesilaos** [comment]
Very well!  Usually this takes about a week.  Let's wait.

**Comment by protesilaos** [comment]
@pprevos I am merging this.  I checked your previous commits and we are just on the limit.  There should be no problem with this one.  Though the next will definitely need copyright assignment.

Thanks again for your contirbution!

**Comment by pprevos** [comment]
Thanks Prot, no need to delete the fork just yet. I'll let you know when the copyright assignment is sorted.

**Comment by protesilaos** [comment]
Thank you!

**Pull request merged**
