### PR TITLE
Fix denote--filetype-heuristics for md files when no key regexps match

### PR DESCRIPTION
**Pull request by jeanphilippegg**
`denote--filetype-heuristics` should always return an md filetype if the
file extension is md even if no key regexps match in the file. In that
case, we use the first md type in `denote-file-types`.

markdown-yaml should appear before markdown-toml in `denote-file-types`
because it used to be the default markdown type of
denote--filetype-heuristics.

### CODE REVIEW

**Comment by protesilaos** [comment]
Thank you!

> markdown-yaml should appear before markdown-toml [...]

This will be problematic if we make it a `defcustom`.  We cannot guarantee how the user will write the values.

**Comment by jeanphilippegg** [comment]
> This will be problematic if we make it a `defcustom`. We cannot guarantee how the user will write the values.

I meant to say that the default should be markdown-yaml before markdown-toml. This is not mandatory. If the user change the order, the consequence will be that markdown-toml will be prefered over markdown-yaml when there is no key regexp matches.

**Comment by protesilaos** [comment]
Ah okay, thanks for the clarification!

**Comment by protesilaos** [comment]
Shall I merge this, or do you want to tweak it further?

**Comment by jeanphilippegg** [comment]
It is complete. Defaulting to the first filetype when no key regexps match is documented in the *internal* function `denote--filetype-heuristics`. Maybe we would like to also make this known to the users? (Defaulting to markdown-yaml was not documented in the previous versions.)

**Comment by protesilaos** [comment]
I think documenting it is not needed.  It adds too much to the doc string.  If a problem arises, we deal with it on the spot and adapt things accordingly.

What do you think?

**Comment by jeanphilippegg** [comment]
That's good with me!

**Comment by protesilaos** [comment]
Merged.  Thank you!

**Pull request merged**
