### PR TITLE
Add denote-rename-file-using-front-matter and denote-rename-marked-fi…

### PR DESCRIPTION
**Pull request by jeanphilippegg**
I have not checked your command. I will check it now.

### CODE REVIEW

**Comment by jeanphilippegg** [comment]
It is exactly the same code! Yours is better, because it uses your latest renaming of functions. Don't merge this pull request.

One comment: If I had not read the mailing lists, it would not be clear to me what `reverse` means in `denote-reverse-rename-file`. I think `denote-rename-file-using-front-matter` is clearer.

**Comment by protesilaos** [comment]
> It is exactly the same code! Yours is better, because it uses your latest renaming of functions. Don't merge this pull request.

Okay.  There is still scope for `denote-rename-marked-files-using-front-matter`, but I guess you want to tweak it?

> I think `denote-rename-file-using-front-matter` is clearer.

Agreed!  I used this intentional for the work-in-progress.  Will you rename it as part of this PR or shall I do it now?

**Comment by jeanphilippegg** [comment]
Also, to retrieve the keywords, maybe use `denote--extract-keywords-from-front-matter` instead of `denote--front-matter-keywords`. The former seems more robust, because it does the right job for each file types.

I will force-push these modifications so you can see the final result.

**Comment by protesilaos** [comment]
Yes, I just noticed the `denote--extract-keywords-from-front-matter`.  I had forgotten about it.  Sorry!

**Comment by jeanphilippegg** [comment]
> Yes, I just noticed the `denote--extract-keywords-from-front-matter`. I had forgotten about it. Sorry!

No worry!

I just pushed the changes. Note that the identifier in the front matter is irrelevant and not checked, so I remove it from the user error.

Also, `denote-rename-marked-files-using-front-matter` does not check if the buffers are modified.

**Comment by protesilaos** [comment]
Merged.  Thank you!

**Comment by jeanphilippegg** [comment]
I would also remove this from the docstring: "This basically is the inverse of `denote-rename-file'". The link between it and `denote-rename-file-using-front-matter` is not so clear.

However, I would add a comment: "The identifier of the file (if any) is never modified."

**Comment by protesilaos** [comment]
Okay, please do it.

**Comment by jeanphilippegg** [comment]
We posted at the same time. I added some suggestions.

**Pull request merged**
