### PR TITLE
Update denote--retrieve-filename-title: remove dashes and capitalize

### PR DESCRIPTION
**Pull request by pprevos**
I made some changes to denote--retrieve-filename-title to replace dashes with spaces and capitalise the link title for better typography when linking Denote attachments.

### CODE REVIEW

**Comment by protesilaos** [comment]
Merged.  Thank you!

**Comment by protesilaos** [comment]
I think it is better to abstract this capitalize+dehyphenate into its own function.  Will do it now.

**Comment by protesilaos** [comment]
Okay, just did it.

* * *

By the way, have you assigned copyright to the Free Software Foundation?  It is necessary if you ever need to make changes that exceed the ~15 line limit (in aggregate).

I can send you the form, if you need it.

**Comment by pprevos** [comment]
Great work. The desluggify function could be useful in my garden :)

I am currently focusing on rebuilding my notes inside of Denote and developing a good workflow, so my contributions will be minor. Happy to complete any form that needs to be filed.

**Comment by protesilaos** [comment]
> The desluggify function could be useful in my garden

Oh, if only we could use Emacs for such tasks!

> I am currently focusing on rebuilding my notes inside of Denote and
> developing a good workflow, so my contributions will be minor.

That fine.  I just mentioned the copyright assignment so that we don't
have to deal with it later.

> Happy to complete any form that needs to be filed.

Very well!  Please see below:

```
Please email the following information to assign@gnu.org, and we
will send you the assignment form for your past and future changes.

Please use your full legal name (in ASCII characters) as the subject
line of the message.

REQUEST: SEND FORM FOR PAST AND FUTURE CHANGES

[What is the name of the program or package you're contributing to?]

GNU Emacs

[Did you copy any files or text written by someone else in these changes?
Even if that material is free software, we need to know about it.]



[Do you have an employer who might have a basis to claim to own
your changes?  Do you attend a school which might make such a claim?]


[For the copyright registration, what country are you a citizen of?]


[What year were you born?]


[Please write your email address here.]


[Please write your postal address here.]





[Which files have you changed so far, and which new files have you written
so far?]
```

**Comment by protesilaos** [comment]
Note that I do not need to see the confirmation you will eventually get from the FSF.  Your word will suffice.

**Pull request merged**
