### PR TITLE
Fontification more precise

### PR DESCRIPTION
**Pull request by jeanphilippegg**

### CODE REVIEW

**Comment by protesilaos** [comment]
Thanks!

Shouldn't this have `nil t` as well?

```
(5 'denote-faces-extension)
```

**Comment by jeanphilippegg** [comment]
I removed it because I thought we wanted an extension. You can add it if you want to fontify even when there is no extension.

**Comment by protesilaos** [comment]
> I removed it because I thought we wanted an extension. 

We only need an extension for what we consider "notes".  Otherwise it is okay to have a file without an extension (it would normally happen with the Denote rename command).

**Comment by protesilaos** [comment]
Yes/

**Comment by jeanphilippegg** [comment]
This pull request does not bring anything if the extension is optional. I am closing it.

**Comment by protesilaos** [comment]
> This pull request does not bring anything if the extension is optional. I am closing it.

Okay then.

**Pull request closed without merging**
