### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by jeanphilippegg**
No functional changes, just some refactors and removal of unnecessary code.

### CODE REVIEW

**Comment by jeanphilippegg** [comment]
I have made additional cleanups and fixes.

Just a few general comments on programming:
- I have made the `signature` parameter optional in a few internal functions (I included `denote-format-file-name` among those). In general, I think optional parameters are less necessary for internal functions. In this case, I think making it non optional simplifies the code.
- I have removed some checks in multiple functions. I think it is not necessary to ensure that a paramater is of given type, particularly for internal functions. I think it makes the code harder to read.

**Comment by protesilaos** [comment]
Thank you @jeanphilippegg! I noticed you pushed some changes. Please let me know when you are done, so that I proceed to merged this.

**Comment by jeanphilippegg** [comment]
It is ready to be merged!

**Comment by jeanphilippegg** [comment]
I added one more commit. Still ready to be merged!

**Comment by jeanphilippegg** [comment]
I have added a few commits. It is ready to be merged!

**Comment by protesilaos** [comment]
Merged. Thank you!

**Pull request merged**
